"""Simulation engine that advances drones turn by turn."""

from typing import Dict, Tuple, List
from src.models import Drone, Map, Connection, DroneStatus
from .pathfinder import PathFinder


class SimulationEngine:
    """Advance the simulation and enforce movement constraints.

    The engine validates each turn, updates drone positions, and tracks
    reservations in zones and links to prevent invalid congestion.

    Attributes:
        _drones: Mapping of drone ids to drone instances.
        _running: Whether the simulation is active.
        _turn: Current turn counter.
        _map: The map being simulated.
        _path_finder: Pathfinder used to compute routes.
        _reservations: Per-zone and per-time occupancy reservations.
        _link_res: Per-link and per-time capacity reservations.
        _nb_drones: Number of drones in the simulation.
        _turn_moves: Move log emitted during the current turn.
    """

    def __init__(self, sim_map: Map) -> None:
        """Create an empty simulation engine for a map.

        Args:
            sim_map: Map whose topology and metadata will drive the simulation.
        """
        self._drones: Dict[str, Drone] = {}
        self._running: bool = False
        self._turn: int = 0
        self._map: Map = sim_map
        self._path_finder: PathFinder = PathFinder()
        self._reservations: Dict[Tuple[str, int], int] = {}
        self._link_res: Dict[Tuple[Connection, int], int] = {}
        self._nb_drones: int
        self._turn_moves: List[str]

    def register_drone(self, drone: Drone) -> None:
        """Register a drone in the engine.

        Args:
            drone: Drone instance to add to the active simulation.
        """
        self._drones[drone.id] = drone

    def set_nb_drones(self, nb_drones: int) -> None:
        """Set the expected number of drones in the simulation.

        Args:
            nb_drones: Total drone count.
        """
        self._nb_drones = nb_drones

    def get_nb_drones(self) -> int:
        """Return the configured number of drones.

        Returns:
            Number of drones in the simulation.
        """
        return self._nb_drones

    def get_turn_moves(self) -> List[str]:
        """Return the move log for the current turn.

        Returns:
            List of move strings generated by the last processed turn.
        """
        return self._turn_moves

    def get_drones(self) -> Dict[str, Drone]:
        """Return all drones managed by the engine.

        Returns:
            Mapping of drone ids to drone instances.
        """
        return self._drones

    def get_turn(self) -> int:
        """Return the current simulation turn number.

        Returns:
            Current turn index.
        """
        return self._turn

    def get_link_res(self) -> Dict[Tuple[Connection, int], int]:
        """Return the current link reservation map.

        Returns:
            Mapping of ``(connection, time_step)`` to reservation counts.
        """
        return self._link_res

    def check_connectivity(self) -> None:
        """Verify that a path exists from start to end.

        Raises:
            RuntimeError: If no valid route connects the start and goal zones.
        """
        if not self._path_finder.base_dijkstra(
                self._map.get_zones(),
                self._map.get_adj_list(),
                self._map.get_start(),
                self._map.get_end()
                ):
            raise RuntimeError(
                "Critical error: unable to find a path between start and goal")

    def calculate_paths(self, heuristics: bool) -> None:
        """Compute the planned route for every drone.

        Args:
            heuristics: Whether the pathfinder should use heuristic guidance.
        """
        for d in self._drones.values():
            d.path = self._path_finder.time_dijkstra(
                    self._map,
                    d,
                    self._reservations,
                    self._link_res,
                    self._map.get_end(),
                    heur=heuristics
                )
            start: str = self._map.get_start()
            end: str = self._map.get_end()
            current_pos = start

            for node in d.path:
                target_node = node[0]
                time_step = node[1]
                if (target_node != start and target_node != end):
                    self._reservations[
                            node] = self._reservations.get(node, 0) + 1

                conn = self._map.get_connection(current_pos, target_node)
                if conn:
                    edge: Tuple[Connection, int] = (conn, time_step)
                    self._link_res[edge] = self._link_res.get(edge, 0) + 1
                    if self._map.is_restricted(target_node):
                        edge = (conn, time_step - 1)
                        self._link_res[edge] = self._link_res.get(edge, 0) + 1
                current_pos = target_node

    def start(self) -> None:
        """Start the simulation loop."""
        self._running = True

    def stop(self) -> None:
        """Stop the simulation loop."""
        self._running = False

    def is_running(self) -> bool:
        """Return whether the simulation is active.

        Returns:
            ``True`` while the engine is running, otherwise ``False``.
        """
        return self._running

    def _validate_moves(self) -> None:
        """Validate that all planned moves obey zone and link capacity rules.

        Raises:
            RuntimeError: If a drone attempts to violate a hub or link capacity.
        """
        intents_zone: Dict[Tuple[str, int], List[str]] = {}
        intents_conn: Dict[Tuple[Connection, int], List[str]] = {}

        for d in self._drones.values():
            if not d.path:
                continue
            if d.current_location:
                node = d.path[0]
                if node not in intents_zone:
                    intents_zone[node] = []
                intents_zone[node].append(d.id)
                if node[0] != d.current_location:
                    conn = self._map.get_connection(
                            d.current_location, node[0])
                    if not conn:
                        raise RuntimeError(
                            f"Invalid movement (turn {self._turn}): "
                            f"no connection ({d.current_location}-{node[0]})")
                    edge: Tuple[Connection, int] = (conn, node[1])
                    if edge not in intents_conn:
                        intents_conn[edge] = []
                    intents_conn[edge].append(d.id)
                    if node[1] == self._turn + 1:
                        edge = (conn, node[1] - 1)
                        if edge not in intents_conn:
                            intents_conn[edge] = []
                        intents_conn[edge].append(d.id)
                if len(d.path) > 1 and d.path[1][1] == self._turn + 1:
                    node = d.path[1]
                    if node not in intents_zone:
                        intents_zone[node] = []
                    intents_zone[node].append(d.id)
            else:
                node = d.path[0]
                if node not in intents_zone:
                    intents_zone[node] = []
                intents_zone[node].append(d.id)
                if len(d.path) > 1 and d.path[1][1] == self._turn + 1:
                    node = d.path[1]
                    if node not in intents_zone:
                        intents_zone[node] = []
                    intents_zone[node].append(d.id)

        zones = self._map.get_zones()
        for iz, drones in intents_zone.items():
            zone = iz[0]
            if zone == self._map.get_start() or zone == self._map.get_end():
                continue
            if len(drones) > zones[zone].metadata.max_drones:
                raise RuntimeError(
                    f"Hub '{zone}' Max Capacity Violation (turn {self._turn})")
            elif zones[zone].metadata.zone_type == "blocked":
                raise RuntimeError(
                   f"Trying to enter Blocked Hub '{zone}' (turn {self._turn})")
        for ic, drones in intents_conn.items():
            conn = ic[0]
            if len(drones) > conn.max_link_capacity:
                raise RuntimeError(
                        f"Link Capacity Violation (turn {self._turn}): "
                        f"'{ic[0]}:{drones}'")

    def process_turn(self) -> None:
        """Process a single simulation turn.

        Raises:
            ValueError: If a drone path contains a stale or impossible step.
            RuntimeError: If a movement violates the simulation constraints.
        """
        self._turn += 1
        self._turn_moves = []

        self._validate_moves()

        for d in self._drones.values():
            if len(d.path) and d.status != DroneStatus.DELIVERED:
                if d.path[0][1] == self._turn:
                    if d.path[0][0] == d.current_location:
                        d.status = DroneStatus.WAITING
                    elif d.current_location is None:
                        d.status = DroneStatus.IN_TRANSIT
                    else:
                        d.status = DroneStatus.MOVING
                    d.current_location = d.path.pop(0)[0]
                    if d.status != DroneStatus.WAITING:
                        self._turn_moves.append(f"{d.id}-{d.current_location}")

                elif d.path[0][1] == self._turn + 1:
                    end1 = d.current_location
                    end2 = d.path[0][0]
                    d.current_location = None
                    d.status = DroneStatus.IN_TRANSIT
                    self._turn_moves.append(f"{d.id}-{end1}-{end2}")
                else:
                    raise ValueError(
                        f"Drone '{d.id}' with path node in the past!"
                        f"{d.path}")
            else:
                d.status = DroneStatus.DELIVERED

    def calculate_all_occupancies(self) -> Dict[str, int]:
        """Calculate how many drones occupy each zone.

        Returns:
            Mapping of zone names to drone counts.
        """
        return {z: sum(z == d.current_location for d in self._drones.values())
                for z in self._map.get_zones()}
